continue on minreq

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -112,7 +112,13 @@ jobs:
         run: uv pip install --verbose -e .[${{ matrix.gui }},${{ matrix.canvas }}] --resolution lowest-direct -U --only-binary numpy --only-binary wxpython
 
       - name: 🧪 🔁 Test again
-        run: uv run pytest -v --color yes tests -W ignore
+        shell: bash
+        continue-on-error: true
+        run: |
+          if ! uv run pytest -v --color yes tests -W ignore; then
+            echo "::warning::Min requirements test failed."
+            exit 0  # Prevent step failure
+          fi
 
       - uses: codecov/codecov-action@v5
         with:
